### ISSUE TITLE
Run failed when run multi programs at the same time

### ISSUE THREAD

**Issue by chen1i6c04** [ythuang0522/homopolish#22]
Hi
I try to run multi `homopolish` programs at the same time and usually fail.
Error message  as below:
```
Traceback (most recent call last):
  File "/home/chen1i6c04/Tools/homopolish-0.1/homopolish.py", line 52, in <module>
    main()
  File "/home/chen1i6c04/Tools/homopolish-0.1/homopolish.py", line 38, in main
    FLAGS.output_dir, FLAGS.minimap_args, FLAGS.mash_threshold, FLAGS.download_contig_nums, FLAGS.debug, FLAGS.meta)
  File "/home/chen1i6c04/Tools/homopolish-0.1/modules/polish_interface.py", line 270, in polish_genome
    download_contig_nums, contig_name, contig.id)
  File "/home/chen1i6c04/Tools/homopolish-0.1/modules/polish_interface.py", line 45, in mash_select_closely_related
    contig_id)
  File "/home/chen1i6c04/Tools/homopolish-0.1/modules/mash.py", line 36, in dist
    os.remove('temp.tab')
FileNotFoundError: [Errno 2] No such file or directory: 'temp.tab'
```
This error is likely because the file `temp.tab` wrote to the same path, do you have any idea?
Thanks

**Comment by J-I-P** [comment]
Hi, we update the new version to fix this problem.
You can try to run the program again. If there is any problem, you can comment below, thanks.

**Comment by chen1i6c04** [comment]
Program can run successfully. 
Thanks
