### ISSUE TITLE
key error 10

### ISSUE THREAD

**Issue by hiagro** [ythuang0522/homopolish#60]
Hi, I am getting this error when trying to run homopolish:

[hi.silva@login2 genome_polishing_13]$ homopolish polish -a out_medaka_TAQ13_genome_polished.fasta -s bacteria.msh -m R9.4.pkl -o homopolished_output
[2023/07/04 10:43] INFO: RUN-ID: contig_1
[2023/07/04 10:43] INFO: Stage: Select closely-related genomes
TIME Select closely-related genomes: 11 MINS 51 SECS.
[2023/07/04 10:55] INFO: Stage: Download closely-related genomes
 INFO: 20 homologous sequence need to download: 
Downloaded GCA_002898415.1_ASM289841v1_genomic.fna.gz
Downloaded GCA_002898475.1_ASM289847v1_genomic.fna.gz
Downloaded GCA_002688625.1_ASM268862v1_genomic.fna.gz
Downloaded GCA_900299175.1_Xanthomonas_fuscans_subsp._aurantifolii_AM_0519_genomic.fna.gz
Downloaded GCA_002079965.1_ASM207996v1_genomic.fna.gz
Downloaded GCA_001610915.1_ASM161091v1_genomic.fna.gz
Downloaded GCA_002837255.1_ASM283725v1_genomic.fna.gz
Downloaded GCA_000175135.1_ASM17513v1_genomic.fna.gz
Downloaded GCA_003957475.1_ASM395747v1_genomic.fna.gz
Downloaded GCA_001610795.1_ASM161079v1_genomic.fna.gz
Downloaded GCA_004329295.1_ASM432929v1_genomic.fna.gz
Downloaded GCA_001610815.1_ASM161081v1_genomic.fna.gz
Downloaded GCA_004329275.1_ASM432927v1_genomic.fna.gz
Downloaded GCA_000175155.1_ASM17515v1_genomic.fna.gz
Downloaded GCA_020879395.1_ASM2087939v1_genomic.fna.gz
Downloaded GCA_004329265.1_ASM432926v1_genomic.fna.gz
Downloaded GCA_015243835.1_ASM1524383v1_genomic.fna.gz
Downloaded GCA_016495605.1_ASM1649560v1_genomic.fna.gz
Downloaded GCA_001401605.1_Xff_LMG826_genomic.fna.gz
Downloaded GCA_002759215.3_ASM275921v3_genomic.fna.gz
TIME Download closely-related genomes: 0 MINS 3 SECS.
[M::mm_idx_gen::0.128*1.01] collected minimizers
[M::mm_idx_gen::0.161*1.01] sorted minimizers
[M::main::0.161*1.01] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.167*1.01] mid_occ = 100
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.171*1.01] distinct minimizers: 491914 (99.13% are singletons); average occurrences: 1.034; average spacing: 9.997
[M::worker_pipeline::55.380*1.00] mapped 4030 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -cx asm5 --cs=long -t 1 /blue/jhuguet/hi.silva/genome_polishing_13/homopolished_output/debug/contig_1/contig_1.fasta /blue/jhuguet/hi.silva/genome_polishi
ng_13/homopolished_output/debug/contig_1/All_homologous_sequences.fasta.gz
[M::main] Real time: 55.401 sec; CPU: 55.313 sec; Peak RSS: 0.346 GB
55.44363355636597
[2023/07/04 10:56] INFO: Stage: Homologous retrieval
TIME Homologous retrieval: 1 MINS 58 SECS.
[2023/07/04 10:58] INFO: Stage: Prediction
Traceback (most recent call last):
  File "/apps/homopolish/0.3.3/bin/homopolish", line 10, in <module>
    sys.exit(main())
  File "/apps/homopolish/0.3.3/lib/python3.7/site-packages/homopolish/homopolish.py", line 38, in main
    FLAGS.output_dir, FLAGS.minimap_args, FLAGS.mash_threshold, FLAGS.download_contig_nums, FLAGS.debug, FLAGS.meta)
  File "/apps/homopolish/0.3.3/lib/python3.7/site-packages/modules/polish_interface.py", line 303, in polish_genome
    finish = homopolish(contig_name, minimap_args, threads, db_path, model_path, contig_output_dir, dataframe)
  File "/apps/homopolish/0.3.3/lib/python3.7/site-packages/modules/polish_interface.py", line 90, in homopolish
    result = prediction.predict(dataframe, model_path, threads, contig_output_dir)
  File "/apps/homopolish/0.3.3/lib/python3.7/site-packages/modules/prediction.py", line 19, in predict
    model = joblib.load(model)
  File "/apps/homopolish/0.3.3/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 585, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/apps/homopolish/0.3.3/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 504, in _unpickle
    obj = unpickler.load()
  File "/apps/homopolish/0.3.3/lib/python3.7/pickle.py", line 1088, in load
    dispatch[key[0]](self)
KeyError: 10

**Comment by ythuang0522** [comment]
Hi @hiagro , we found your version is 0.3.3 which may lead to the dependency issue. Can you please reinstall using the latest version (0.4.1)? 
```
conda config --set channel_priority flexible
conda create -n homopolish -c conda-forge -c bioconda homopolish=0.4.1=pyhdfd78af_1
```

Yao-Ting
